<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite skipped="1" hostname="DESKTOP-81M737A" name="OrderCard.LoginToOpal" tests="2" failures="0" timestamp="12 Sep 2017 13:03:30 GMT" time="0.685" errors="0">
  <testcase name="testLoginToOpal" time="0.685" classname="OrderCard.LoginToOpal"/>
  <testcase name="loginToOpalForAllUsers" classname="OrderCard.LoginToOpal">
    <skipped/>
  </testcase> <!-- loginToOpalForAllUsers -->
=======
<testsuite skipped="0" hostname="DESKTOP-81M737A" name="OrderCard.LoginToOpal" tests="1" failures="0" timestamp="04 Sep 2017 22:28:24 GMT" time="0.000" errors="1">
  <testcase name="LogintoOpal" time="0.000" classname="OrderCard.LoginToOpal">
    <error type="org.testng.TestNGException" message="
Data Provider public java.util.HashMap OrderCard.LoginToOpal.getData() throws java.io.IOException must return either Object[][] or Iterator&lt;Object&gt;[], not class java.util.HashMap">
      <![CDATA[org.testng.TestNGException: 
Data Provider public java.util.HashMap OrderCard.LoginToOpal.getData() throws java.io.IOException must return either Object[][] or Iterator<Object>[], not class java.util.HashMap
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- LogintoOpal -->
>>>>>>> branch 'master' of https://github.com/pallavimalpure/OpalTest
</testsuite> <!-- OrderCard.LoginToOpal -->
